"""Rule-based summary (used when no LLM is configured) and Markdown/JSON export."""

from __future__ import annotations

from .models import AnalysisReport, Finding, Severity
from .utils import fmt_bytes, fmt_cpu, fmt_pct

# (required rule ids, rule ids that make this hypothesis redundant, text)
HYPOTHESES: list[tuple[set[str], set[str], str]] = [
    (
        {"oom_killed"},
        set(),
        "**Memory exhaustion**: containers are being OOMKilled; each restart drops capacity and in-flight "
        "requests, pushing load onto the surviving replicas.",
    ),
    (
        {"cpu_throttling", "hpa_at_max"},
        set(),
        "**CPU capacity ceiling**: pods are CPU-throttled while the HPA is already at maxReplicas, so the "
        "service cannot scale out of the load and latency grows.",
    ),
    (
        {"cpu_throttling"},
        {"hpa_at_max"},
        "**CPU limits too tight**: CFS throttling is stretching request processing time.",
    ),
    (
        {"pending_pod"},
        set(),
        "**Cluster capacity / scheduling**: replicas are stuck Pending, so the deployment runs below its desired size.",
    ),
    (
        {"logs_db_pool"},
        set(),
        "**Downstream database contention**: the connection pool is exhausted, so requests queue waiting for "
        "a DB connection (often amplified by slow queries).",
    ),
    (
        {"logs_timeout"},
        set(),
        "**Slow downstream dependency**: requests time out waiting on another service.",
    ),
    (
        {"crash_looping", "logs_dns"},
        set(),
        "**Dependency DNS failure**: the container cannot resolve a dependency's Service name at startup and "
        "exits, causing the crash loop.",
    ),
    (
        {"logs_dns"},
        {"crash_looping"},
        "**DNS resolution failures**: a dependency's hostname cannot be resolved.",
    ),
    (
        {"logs_connection"},
        set(),
        "**Unreachable dependency**: connection refused/reset errors point to a downstream outage.",
    ),
    (
        {"node_pressure"},
        set(),
        "**Node contention**: a hosting node is saturated and degrading co-located pods.",
    ),
    (
        {"crash_looping"},
        {"oom_killed", "logs_dns"},
        "**Application crash loop**: the container repeatedly fails after start.",
    ),
    (
        {"container_start_failure"},
        set(),
        "**Broken rollout**: containers cannot start (image or config error).",
    ),
]


def root_cause_hypotheses(findings: list[Finding]) -> list[str]:
    ids = {f.rule_id for f in findings}
    return [text for needed, unless, text in HYPOTHESES if needed <= ids and not unless & ids]


def rule_based_summary(report: AnalysisReport) -> str:
    snap, findings = report.snapshot, report.findings
    counts = report.severity_counts()
    dep = snap.deployment.get("status", {})
    lines = [
        f"### Deployment `{snap.namespace}/{snap.deployment_name}` - health score {report.health_score}/100",
        "",
        f"Replicas: {dep.get('availableReplicas', 0) or 0}/{snap.deployment.get('spec', {}).get('replicas', 1)} "
        f"available · metrics source: {snap.metrics_source} · findings: "
        + ", ".join(f"{n} {s}" for s, n in counts.items() if n),
        "",
    ]
    actionable = [f for f in findings if f.severity != Severity.INFO]
    if not actionable:
        lines.append("No bottlenecks detected. The deployment looks healthy for the observed window.")
    else:
        hyps = root_cause_hypotheses(findings)
        if hyps:
            lines += ["#### Likely root cause", *[f"- {h}" for h in hyps], ""]
        lines.append("#### Top bottlenecks")
        for i, f in enumerate(actionable[:6], 1):
            lines.append(f"{i}. **[{f.severity.value.upper()}] {f.title}** - `{f.resource}`")
            if f.evidence:
                lines.append(f"   - Evidence: {'; '.join(f.evidence[:2])}")
            lines.append(f"   - Fix: {f.recommendation}")
        lines.append("")
    lines.append("_Summary generated by the rule engine. Configure an LLM for an agentic root-cause analysis._")
    return "\n".join(lines)


def to_markdown(report: AnalysisReport) -> str:
    snap = report.snapshot
    out = [
        f"# Bottleneck report: {snap.namespace}/{snap.deployment_name}",
        "",
        f"- Collected at: {snap.collected_at}",
        f"- Health score: **{report.health_score}/100**",
        f"- Summary source: {report.summary_source}" + (f" ({report.llm_model})" if report.llm_model else ""),
        f"- Metrics source: {snap.metrics_source}" + (f" ({snap.prometheus_url})" if snap.prometheus_url else ""),
        "",
        "## Summary",
        "",
        report.summary_markdown,
        "",
        "## Findings",
        "",
    ]
    for f in report.findings:
        out += [
            f"### [{f.severity.value.upper()}] {f.title}",
            f"- Resource: `{f.resource}` · Category: {f.category}",
            f"- {f.description}",
            *[f"  - {e}" for e in f.evidence],
            f"- **Recommendation:** {f.recommendation}",
            "",
        ]
    out += [
        "## Containers",
        "",
        "| Pod | Container | Phase | Restarts | CPU use/req/lim | Throttle | Mem use/lim |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for c in report.containers:
        out.append(
            f"| {c.pod} | {c.container} | {c.phase} | {c.restarts} | "
            f"{fmt_cpu(c.cpu_usage)}/{fmt_cpu(c.cpu_request)}/{fmt_cpu(c.cpu_limit)} | "
            f"{fmt_pct(c.throttle_ratio)} | {fmt_bytes(c.mem_usage)}/{fmt_bytes(c.mem_limit)} |"
        )
    if report.warnings or snap.warnings:
        out += ["", "## Collection warnings", "", *[f"- {w}" for w in [*snap.warnings, *report.warnings]]]
    return "\n".join(out) + "\n"
